### ISSUE TITLE
Asus Flip c302

### ISSUE THREAD

**Issue by nate8199** [pwdonald/chromeos-qemu-docker#9]
I just got this running on a Asus Flip c302 m3,4gb ram
Version 63.0.3239.140 (Official Build) (64-bit)

**Comment by vincowl** [comment]
@nate8199 I have a c302, but cannot manage to map ports. I used the second way (developer mode without termux). Docker can be managed by a normal session only with the -H option even if I updated my bashrc. localhost:10080 leads to errors too. Any hint please ?
